### ISSUE TITLE
[path]

### ISSUE THREAD

**Issue by leszekjocz** [lingdb/ielex2#15]
The proposed description, example, and justification are:

"Most generic, unspecified term for a long piece of hard ground along which people can travel from one place to another. Avoid terms specifically referring to a "route"."

"There is a road/path to the next village."

"Given that there The most frequent, basic term should be chosen. This is culturally specific, depending also on economic and environmental factors."

***

I think that we should name the term "path/road" and not just "path" and clearly emphasize the role of cultural factors in choosing of the proper word in a given language.
I'm pretty convinced that in all European lagnuages and in many (if not most) Indo-European languages the term for 'path' is semantically more complex than the term for "road" (and when the term is derived from 'road', which happens, also morphologically more complex).

**Comment by tonyakdewey** [comment]
We had discussed making this 'footpath' rather than 'path' to make clear we are excluding travel by vehicle. I have to say that as an American, 'footpath' is something I am aware exists in other parts of the world, but not a term I would often use (you know we love our cars on this side of the Atlantic). In fact, I can't really use 'path' without some sort of modifier (bike path), or I would use 'trail' (hiking trail, running trail, walking trail).

**Comment by obelyaev** [comment]
It seems that in many cases the distinguishing factor is width/breadth rather than use by vehicles per se. E.g. in Russian, *trop(ink)a* 'footpath' is a semantically very specific term (a narrow, partly overgrown path in the woods). A less marked Russian term that captures the 'vehicle-ness' distinction would be the diminutive of 'road', *dorožka*: this is the word that is used for things like bike or pedestrian paths (*velosipednaja dorožka* 'bike path', *pešexodnaja dorožka* 'pedestrian path'). The choice between "doroga" and "dorožka" is a minor issue, as the cognate set will be the same, but it feels somewhat strange to choose this clearly secondary term as the Swadesh lexeme.

Ossetic is similar: like in English, 'footpath' is literally a compound 'foot' + 'path / road'. But the term is clearly more morphologically complex than 'path' and also less basic: it is not used unless one wants to stress that the path is only navigable on foot.

Thus, overall, I agree with Leszek's suggestion of using 'path/road'.

**Comment by m-scarborough** [comment]
'path' was a difficult word and took awhile to decide on a definition.  The justification for defining it as it currently stands was because of the semantic space occupied by 'path' as the most basic term would likely be different depending on whether the language is being used in an agrarian or modern industrial society.  (Attempting to avoid triggering less basic or more specific terms like '(foot/bike/sheep/etc.)path' 'motorway', 'highway' etc.) As such, I agree renaming the term to 'path/road' is more appropriate.

**Comment by leszekjocz** [comment]
I live from my childhood near to woods, I go every year to pick mushrooms, I know how to get to neighbouring villages through woods, etc.
However, "path" is something very specific to me and somehting like "There is a path to the next village." is a nonsense for me. There can be only a "road" "to the next village" for me.

**Comment by BrittaIrslinger** [comment]
In German, a path is something small, only for walking (humans or animals), while on a road, you can either walk or drive by vehicle. With regard to this broader usage, road is the more basic word. The same applies for Brittonic (remember the remark on Breton by Steven Hewitt). In our group discussion, Paul had argued against road, because to him it is something you have to drive on. It is possible that this is a special problem of English then, which we should we solve by a remark in the  description?

**Comment by tonyakdewey** [comment]
How about "There is a path around the lake" (or something like that) for the example sentence? Does this solve the problem?

**Comment by cormacanderson** [comment]
Renaming as path/road is quite a good idea I think. We don't really want to force either, because which is more basic is likely to be quite specific to the individual language. Most of us agree that the "road" word is more basic in our languages, but it could be that elsewhere in the world, the "path" word is. Tonya's example might well be an improvement: does that sound better to you @leszekjocz . More broadly, this is maybe the only case, or certainly the most striking one, where we deliberately keep open the ambiguity and allow cultural factors to determine the choice of lexeme. Do you all think that is okay, justified here?

**Comment by leszekjocz** [comment]
I don't like the Tonya's examle because it makes for me 'path' the only possible meaning and excludes the meaning 'road'. And as I understand we want to keep both meanings for this term and choose the most appropriate meaning for a concrete language/enviroment.

**Comment by tonyakdewey** [comment]
OK, how about "There is a road/path through the woods"?  That leaves the ambiguity open.

**Comment by cormacanderson** [comment]
Given all these difficulties, this meaning was selected for exclusion, so I'll close this thread now.
