### ISSUE TITLE
List of DEFINITELY excluded meanings?

### ISSUE THREAD

**Issue by tonyakdewey** [lingdb/ielex2#16]
Would it be possible to get a list of the meanings that we decided are definitely excluded last weekend?  I only wrote down about half of them, I think, and I don't want to duplicate work.

**Comment by leszekjocz** [comment]
It would be really helpful, especially since we discussed many meaning in two separate groups.

**Comment by cormacanderson** [comment]
Definitely excluded are: AT, BECAUSE, IF, IN, SOME, AND, WIFE, OTHER, ALL, BLUNT, ROPE, SQUEEZE, STAB, SPLIT, ANIMAL, FEW, HE, FLOW. We've since been through the rest of the meanings and have a shortlist of 19, of which we can lose 7. By extension of the general principles involved in losing the first 18, WITH, MANY and HUSBAND look like good candidates for exclusion, although there are a number of others that are also problematic. We'll try to finalise the list in the next few days and tomorrow I will send around a general email with the current best 100.

**Comment by tonyakdewey** [comment]
Thanks, Cormac!  I thought those of us in the one room had also decided to eliminate SNAKE?  But I could be mistaken.

**Comment by m-scarborough** [comment]
I don't like SNAKE just because of its non-straightforwardness in Indo-European languages, but cross-linguistically it might not be so bad...

**Comment by cormacanderson** [comment]
Aviva and @PaulHeggarty and I sat down last night and whittled down the candidates for exclusion. We now have a working 200 list, as well as the 100 list we had come up with previously. I will send both of these around to the group soon. I'll also mark the excluded meanings on the Wiki as 01 EXCLUDE [meaning], so that you can see them there. Given all that, I'll close this thread.
PS @tonyakdewey @m-scarborough , sorry, but SNAKE stays in ;P
