### ISSUE TITLE
Add filtering by 'Not Sw.' fields

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/ielex2#6]
Edit by @runjak:
On the lexeme table forms (by 1 meaning or by 1 language), add a toggle filter to show/hide lexemes marked as Not Sw.

**Comment by PaulHeggarty** [comment]
On all data entry forms, the column headers, and submit button, should remain visible as a page header when one scrolls down the page.  (So the submit button need not hover anyway.)

**Comment by PaulHeggarty** [comment]
What is the 'cancel' button?  Is it 'undo', and if so, rename it to 'undo'.

**Comment by tonyakdewey** [comment]
Can we have the excluded meanings not show up in the lists? Especially for the ones that have 3+ entries for my languages, it's making my work flow slower, since I'm having to scroll past scads of things that we're not actually going to use.

Also, could we have an option to not show the excluded (not Swadesh term) lexemes?  Again, since I'm having this inherited butterfly collecting problem, I've got twice as many things showing up as I should, and it would go faster if I didn't have them all there.

**Comment by runjak** [comment]
Hg commits `f911e0815ebe98a4a9ff3e093611633288a7e843` and `8ec9e67deac2be3173e12746492b0978c491d8c5` address this issue and will be deployed with the next update.
